### ISSUE TITLE
remote-exec provisioner error with GCP

### ISSUE THREAD

**Issue by jimcaldwelljr** [rjsgn/outline-terraform-ansible#3]
I've followed all steps and get this error on final build 

Error: remote-exec provisioner error
│ 
│   with google_compute_instance.outline_vm,
│   on outline_vm.tf line 34, in resource "google_compute_instance" "outline_vm":
│   34:   provisioner "remote-exec" {
│ 
│ timeout - last error: dial tcp 35.226.108.46:22: i/o timeout

**Comment by elvinasn** [comment]
Did you manage to fix it?

**Comment by rjsgn** [comment]
I haven't had a chance to look at this yet. @jimcaldwelljr Are you still seeing this error?

**Comment by elvinasn** [comment]
@rjsgn I am seeing this error.

**Comment by rjsgn** [comment]
@elvinasn I just pushed an update. Can you check if the problem still persists for you? Thanks!
